version: '3'

services:
    rabbitMQ:
        image: rabbitmq:3.7.5-management-alpine
        hostname: rabbit1
        container_name: rabbit1
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: vhost
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq1"
        networks:
            - "rabbitmq"
        #volumes:
            #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
            #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
            #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
    phppublisher:
        build: publisher_php/
        restart: always
        container_name: publisher_php
        ports:
            - 8000:80
        networks:
            - "rabbitmq"


networks:
    rabbitmq:
